### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by SubatomicCat** [armonge/gnome-shell-extension-focusli#28]
Can't install version 5. Get this error: 

`Extension "focusli@armonge.info" had error: TypeError: GObject.registerClass() used with invalid base class (is PopupBaseMenuItem)`

GNOME Shell 3.30.2

**Comment by armonge** [comment]
@SubatomicCat is there any chance you could update your gnome? I'm currently on 3.36 and can't really test on 3.30

Also, due to some changes in recent Gnome JS the current extension code will definitely not work on 3.30 since https://github.com/armonge/gnome-shell-extension-focusli/commit/4ad8e07e6f9ae90516836a8a32bc7a708bc32186

**Comment by SubatomicCat** [comment]
I see. I will look into doing that. I am fairly new to this so I gotta figure out if it will not screw up my OS.

**Comment by SubatomicCat** [comment]
I see. I will look into doing that. I have never tried this so I gotta figure out if it will screw up my OS.
